pipeline{
    agent any
    stages{
        stage("Git Checkout"){
            steps{
                git branch: 'main', url: 'https://github.com/siswarnava-sss/ecommerce2'
            }
        }
        stage("Unit Test"){
            steps{
                sh 'mvn test'
            }
        }
        stage("Integrations Test"){
            steps{
                sh 'mvn verify -DskipUnitTest'
            }
        }
    }
}
