pipeline{
    agent any
    tools {
        maven 'maven'
    }
    stages{
        stage("Git Checkout"){
            steps{
                git branch: 'main', url: 'https://github.com/siswarnava-sss/ecommerce2'
            }
        }
        stage("Go to backend folder"){
            steps{
                sh 'mvn -f ./backend/*'
            }
        }
        stage("Make jar file"){
            steps{
                sh 'mvn claen package -DskipTests=true'
            }
        }
    }
}
